### ISSUE TITLE
[Guide] Searching in guide docs

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet.github.io#216]
[https://jovial-villani-909c3b.netlify.com/guide/introduction](https://jovial-villani-909c3b.netlify.com/guide/introduction)

**Comment by herflis** [comment]
![image](https://user-images.githubusercontent.com/6968860/42262261-11f96344-7f6b-11e8-86b7-c1028a106c77.png)

![image](https://user-images.githubusercontent.com/6968860/42262287-21910dca-7f6b-11e8-9f1a-fbae47c3dca6.png)

![image](https://user-images.githubusercontent.com/6968860/42262308-316c4f16-7f6b-11e8-8d97-ccef2030a9e3.png)

**Comment by herflis** [comment]
![image](https://user-images.githubusercontent.com/6968860/42262350-523642b0-7f6b-11e8-9ac5-c7a20d93b790.png)

**Comment by kultsar** [comment]
Searching seems ok. Have only some suggestions:

- [ ] Access more than 10 results: Might need to add function to search beyond the first 10 hits. At present important results easily remain hidden. Example: user searches for 'content', but the most relevant article, 'Content' (guide/content-repository/content), is not listed. So we could display 10, but might user some form of scrolling or paging so that user can search on for more results.

- [ ] Typing should not collapse the tree: Typing in search box collapses all branches of the tree. Whole tree remains collapsed even after search box is cleared. If I refresh the page, however, the subtree I was in before, expands again.

- [ ] Browse subtrees without switching to other pages: Would be nice to be able to browse subtrees without leaving the page I'm reading at the moment. If I am reading a page but would like to have a look at the items under another subtree, clicking the subtree parent loads the associated page. Perhaps we could place an icon before the parent items that expand the subtree, without leaving my current page.
